### PR TITLE
Add Lithuanian support

### PR DESCRIPTION
**Pull request by dvisockas**
Adds UTF-8 Lithuanian language stemming.
Compiled from: `https://github.com/snowballstem/snowball/blob/master/algorithms/lithuanian.sbl`

### CODE REVIEW

**Comment by aurelian** [comment]
Hi @dvisockas, thanks a lot for your contribution!

Would you be kind to add a spec using this stemmer?

**Comment by dvisockas** [comment]
Hey, @aurelian 
Added spec that tests stemming of lithuanian words.

Note: I upped the json and gem itself versions as I couldn't build it.
Also: When running tests I get an error message `File does not exist: lingua/stemmer_native` so they are only theoretical.

**Comment by dvisockas** [comment]
@aurelian , I dropped `1.8.7` and `1.9.3` from `travis.yml` as they are not supported anymore. Also added `2.3.3` , `2.5.1`, `2.6.5` to test against newer versions. 

What else could I do so that this PR would get merged? :)

**Comment by aurelian** [comment]
Hi @dvisockas -- looks great, thanks a lot, I'm gonna merge it probably this week (ping me if I don't) and release a new version on rubygems.

I'm trying to remember what I did to build a that fat binary gem for windows :)

**Comment by aurelian** [comment]
Hi @dvisockas -- I have released a new version today (2.0) dropping support for ruby 1.8.

Can you rebase your branch and fix the conflicts so I can merge it and release a new gem version (2.0.1)?

**Comment by dvisockas** [comment]
Hey @aurelian, rebased. :)

**Pull request merged**
